---
all:
  children:
    production:
      children:
        down:
          hosts: 
            pm-nod147:
        idle:
          hosts: 
            pm-nod052:
        mixed:
          hosts: 
            pm-nod009:
            pm-nod010:
    python3:
      children:
        mixed:
          hosts: 
            pm-nod146:
  hosts: 
    pm-nod009:
    pm-nod010:
    pm-nod052:
    pm-nod146:
    pm-nod147:
